hh_data <- read.table("exdata-data-household_power_consumption/household_power_consumption.txt",header=TRUE,sep=";")
library(lubridate)
hh_data$Date <- dmy(hh_data$Date)
hh_data$Time <- hms(hh_data$Time)
library(dplyr)
hh_data_filtered <- tbl_df(hh_data)
first_day <- dmy("31/01/2007")
second_day <- dmy("03/02/2007")
hh_data_filtered <- filter(hh_data_filtered,Date > first_day)
hh_data_filtered <- filter(hh_data_filtered,Date < second_day)
dev.off()
plot(as.numeric(as.character(hh_data_filtered$Sub_metering_1)),type="l",ylim=c(0,30),xlab="",ylab="")
par(new=TRUE)
plot(as.numeric(as.character(hh_data_filtered$Sub_metering_2)),type="l",ylim=c(0,30),col="red",xlab="",ylab="")
par(new=TRUE)
plot(as.numeric(as.character(hh_data_filtered$Sub_metering_3)),type="l",ylim=c(0,30),col="blue",xlab="",ylab="")
title(xlab="",ylab="Energy sub metering")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pch=c("l","l","l"),pt.cex=0.8,cex=0.8)
dev.copy(png,"plot3.png")
dev.off()
