hh_data <- read.table("exdata-data-household_power_consumption/household_power_consumption.txt",header=TRUE,sep=";")
library(lubridate)
hh_data$Date <- dmy(hh_data$Date)
hh_data$Time <- hms(hh_data$Time)
library(dplyr)
hh_data_filtered <- tbl_df(hh_data)
first_day <- dmy("31/01/2007")
second_day <- dmy("03/02/2007")
hh_data_filtered <- filter(hh_data_filtered,Date > first_day)
hh_data_filtered <- filter(hh_data_filtered,Date < second_day)
dev.off()
plot(as.numeric(as.character(hh_data_filtered$Global_active_power)),type="l",xlab="",ylab="Gloabl Active Power (kilowatts)")
dev.copy(png,"plot2.png")
dev.off()
